[package]
name = "onyxia-runtime"
description = "GPU executor for compiled Onyxia graphs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck = "1.25.0"
futures = "0.3.31"
naga = { version = "28", features = ["wgsl-out"] }
naga_oil = "0.21"
onyxia-codegen.workspace = true
onyxia-onnx = { version = "0.1.0", path = "../onyxia-onnx" }
pollster = { version = "0.4.0", features = ["macro"] }
thiserror = "2.0.18"
wgpu = "28"

[dev-dependencies]
