[package]
name = "onyxia-onnx"
description = "ONNX model parser for Onyxia"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost = "0.14.3"

[dev-dependencies]

[build-dependencies]
prost-build = "0.14.3"
